### ISSUE TITLE
VariantDetective application

### ISSUE THREAD

**Issue by emilydolivo97** [OLF-Bioinformatics/VariantDetective#10]
Hello, thank you for this package.
 I have 3 questions and I hope you can answer them: 
       - Can we use Variant Detective on reads generated using Oxford Nanopore technology (long reads)? 
       - Can we use it to detect variants in oomycetes? 
       - Can we also detect insertions and deletions in addition to SNPs (Substitutions) and SV ?

**Comment by philcharron-cfia** [comment]
Hi @emilydolivo97,

> Can we use Variant Detective on reads generated using Oxford Nanopore technology (long reads)?

VariantDetective can be used with long reads to predict structural variants at the moment. In order to predict SNPs/INDELs, you will need to either use short reads, or an assembled genome. We are looking to add SNP/INDEL calling using for long reads in a future release.

> Can we use it to detect variants in oomycetes?

Although the benchmarking and testing was performed using bacterial genomes only, I believe it could be applied to other species (such as oomycetes). One limitation is that some of the tools within VariantDetective are being called to work on haploid genomes, whereas oomycetes are typically diploid. This could impact the efficiency of the variant calling.

> Can we also detect insertions and deletions in addition to SNPs (Substitutions) and SV ?

The snp_indel and all_variants modules (using short reads or full genome) do predict short insertions and deletion, as well as SNPs. The structural_variant module will predict large-scale genomic insertions and deletions, 

Hope this helps and thanks for checking out our tool!
